language: r
sudo: false
cache: packages

r_check_args: "--as-cran --run-dontrun"

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
